apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: deploy
  annotations:
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    acme.cert-manager.io/http01-edit-in-place: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.app.com
      # secretName: default-server-secret
      secretName: example-app-tls
  rules:
    - host: www.app.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: test
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test2
                port:
                  number: 80
