apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: deploy
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          # image: phucv2/k8s
          image: test
          imagePullPolicy: Never
          # imagePullPolicy: IfNotPresent
          env:
            - name: NAME
              value: 'testAbc123'
            - name: DB_HOST
              value: 10.0.0.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: deploy
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
