apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: test
          imagePullPolicy: Never
          env:
            - name: NAME
              value: 'testAbc123'
            - name: DB_HOST
              value: 10.10.10.99
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 3000
  type: LoadBalancer
