apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: test
          imagePullPolicy: Never
          env:
            - name: NAME
              value: 'testAbc123'
            - name: DB_HOST
              value: 10.1.0.194
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
