apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: deploy
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  # externalIPs:
  #   - $HOST
  selector:
    app: nginx-ingress
