apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: deploy
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  externalIPs:
    - 192.168.1.103
  selector:
    app: nginx-ingress
